### ISSUE TITLE
node-red-contrib-sap-node node installation Fail from manage palette

### ISSUE THREAD

**Issue by aadi1999** [radu103/node-red-contrib-sap-hana#10]
### What are the steps to reproduce?
 - try to install node-red-contrib-sap-node from manage palette in node-red .
 
### What happens?

 

 If we try to install the sap hana node from manage palette it is failing to install.
 
1. Tested Node-Red Image using

**docker run command** using proxy network able to install SAP Hana node in the specified UserDir.
but same image using **docker compose** file with proxy network installation of SAP node is failing in specified UserDir.
docker run Command :
docker run -it -p 1880:1880 nodered:latest
Please find the attached compose file.
[docker-compose.txt](https://github.com/radu103/node-red-contrib-sap-hana/files/6356681/docker-compose.txt)

 

2.Tried with root user using docker compose file Node installation is failed.

 

Error:

 

node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: failed to map segment from shared object
TypeError: Cannot read property '__stopAllWork' of null
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @sap/hana-client@2.8.16 install: `node checkbuild.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.8.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-21T06_57_45_674Z-debug.log

 

### What do you expect to happen?
-it should install the sap hana node with docker compose also in the specified UserDir.

 

### Please tell us about your environment:

 

- [ ] Node-RED version: 1.2.5
- [ ] Node.js version: v10.19.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Docker / Debian OS
- [ ] Browser: Mozilla firefox/ Google Chrome

**Comment by radu103** [comment]
I runned the nodered container with the recomended command from their home page : ` docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered nodered/node-red.
After that I installed from pallete and it worked just fine.
More info here : https://nodered.org/docs/getting-started/docker
`

**Comment by aadi1999** [comment]
Even for me through docker run command its working fine,
but same image thorugh docker-compose its not working
its not installing in specified UserDir.

**Comment by radu103** [comment]
your docker compose file does not have a reference for mounting persistence volume. Maybe that is the problem.
Based on your response we can agree that it's not a component bug, rather a configuration bug in running the container

**Comment by aadi1999** [comment]
> your docker compose file does not have a reference for mounting persistence volume. Maybe that is the problem.
> Based on your response we can agree that it's not a component bug, rather a configuration bug in running the container

Hi Radu,

With mounting persistence volume also its not working.

Please find the attachment below.
[docker-compose.txt](https://github.com/radu103/node-red-contrib-sap-hana/files/6376897/docker-compose.txt)

**Comment by RMutharaju** [comment]
Hello @radu103 

Can you consider this issue and reopen the same.

**Comment by radu103** [comment]
With the latest docker-compose file, I get this error :
WARNING: Some networks were defined but are not used by any service: data-network
ERROR: Service "nodered" uses an undefined network "data_network"

**Comment by radu103** [comment]
This docker-compose file works and the component is installed ok from "manage palette" for my Docker version 18.09.9, build ca97a20ff1, on Windows OS
[docker-compose -ok.txt](https://github.com/radu103/node-red-contrib-sap-hana/files/6401569/docker-compose.-ok.txt)

**Comment by aadi1999** [comment]
Hi Radu,

We have already tested on window os. It works fine for me also.
The issue can be seen in Debian OS.

We are using base image debian buster slim.

**Comment by radu103** [comment]
I'm sorry but the issue you're is not related to this published component, it is related to other errors
This issue remains closed.

**Comment by RMutharaju** [comment]
@radu103 ,

Can you tell what could cause this error

"node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: **failed to map segment from shared object**
TypeError: Cannot read property '__stopAllWork' of null"

**Comment by radu103** [comment]
It seems to be a problem in the @sap/hana-client npm package. Please ask the owner

**Comment by aadi1999** [comment]
Hi @radu103,

Can you please let us how to reach out the @sap/hana-client npm package owner.
There is no GitHub repository and any contact information can you please share.
We tried to search the owner but we didnt get any reference.

**Comment by radu103** [comment]
This is the package page https://www.npmjs.com/package/@sap/hana-client
